# # Use the official Node.js image as the base image
# FROM node:14

# # Create and set the working directory
# WORKDIR /app

# # Copy the package.json and package-lock.json files
# COPY ./package.json /app

# # Install dependencies
# RUN npm install

# # Copy the rest of the application code
# COPY . /app

# # Expose the port the app runs on (e.g., 3000 if your app uses it)
# EXPOSE 3000

# # Define the command to run the application
# CMD ["node", "index.js"]


# Use an official Node.js runtime as a parent image
FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Environment variables
ENV PORT=8080

# Expose the port
EXPOSE 8080

# Start the app
CMD ["node", "index.js"]

